### ISSUE TITLE
Support for Gatsby V3.0

### ISSUE THREAD

**Issue by Undistraction** [Mrtenz/gatsby-plugin-favicons#10]
> gatsby-plugin-favicons@2.0.0" has incorrect peer dependency "webpack@^4.0.0"

Gatsby has [upgraded its Webpack dependency](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#webpack-upgraded-from-version-4-to-version-5) to v5.

**Comment by Mrtenz** [comment]
Hey @Undistraction, Gatsby made an official plugin for handling favicons and stuff a while ago, called [`gatsby-plugin-manifest`](https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/). It essentially does everything this plugin does and is actively maintained by the Gatsby team, so you're likely better off using that plugin instead.
